# Generated by Django 2.2 on 2022-08-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_type', models.IntegerField(choices=[(1, 'type1'), (2, 'type2'), (3, 'type3')])),
                ('for_type1', models.TextField()),
                ('for_type2', models.CharField(max_length=255)),
                ('for_type3', models.IntegerField()),
            ],
        ),
    ]
