# Generated by Django 4.1 on 2022-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_alter_godmodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="godmodel",
            name="for_type1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="godmodel",
            name="for_type2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="godmodel",
            name="for_type3",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
